ASP_NET_INMN3_PA1.1+sp_wszyscy_Z2/Models/ErrorViewModel.cs
namespace ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ASP_NET_INMN3_PA1.1+sp_wszyscy_Z2/Models/Miasto.cs
namespace ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Models;

public class Miasto
{
    public int Id { get; set; }
    public string? Nazwa { get; set; }
    public uint? Populacja { get; set; }
}

ASP_NET_INMN3_PA1.1+sp_wszyscy_Z2/Models/WitajViewModel.cs
namespace ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Models;

public class WitajViewModel
{
    public string? Imię { get; set; }
    public int? Ilość { get; set; }
}

ASP_NET_INMN3_PA1.1+sp_wszyscy_Z2/Controllers/HomeController.cs
using ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Controllers;
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(
            new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier }
            );
    }
}

ASP_NET_INMN3_PA1.1+sp_wszyscy_Z2/Controllers/MiastaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Data;
using ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Models;

namespace ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Controllers
{
    public class MiastaController : Controller
    {
        private readonly MVCContext _context;

        public MiastaController(MVCContext context)
        {
            _context = context;
        }

        // GET: Miasta
        public async Task<IActionResult> Index(string? szukanaFraza)
        {
            if(_context.Miasta == null)
                Problem("Entity set 'MVCContext.Miasto'  is null.");

            if(String.IsNullOrEmpty(szukanaFraza))
                return View(await _context.Miasta!.ToListAsync());

            ViewData["SzukanaFraza"] = szukanaFraza;

            IQueryable<Miasto> miasta =
                from miasto
                in _context.Miasta
                where miasto.Nazwa!.Contains(szukanaFraza)
                select miasto
                ;

            return View(await miasta.ToListAsync());
        }

        // GET: Miasta/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Miasta == null)
            {
                return NotFound();
            }

            var miasto = await _context.Miasta
                .FirstOrDefaultAsync(m => m.Id == id);
            if (miasto == null)
            {
                return NotFound();
            }

            return View(miasto);
        }

        // GET: Miasta/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Miasta/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nazwa,Populacja")] Miasto miasto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(miasto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(miasto);
        }

        // GET: Miasta/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Miasta == null)
            {
                return NotFound();
            }

            var miasto = await _context.Miasta.FindAsync(id);
            if (miasto == null)
            {
                return NotFound();
            }
            return View(miasto);
        }

        // POST: Miasta/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nazwa,Populacja")] Miasto miasto)
        {
            if (id != miasto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(miasto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MiastoExists(miasto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(miasto);
        }

        // GET: Miasta/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Miasta == null)
            {
                return NotFound();
            }

            var miasto = await _context.Miasta
                .FirstOrDefaultAsync(m => m.Id == id);
            if (miasto == null)
            {
                return NotFound();
            }

            return View(miasto);
        }

        // POST: Miasta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Miasta == null)
            {
                return Problem("Entity set 'MVCContext.Miasto'  is null.");
            }
            var miasto = await _context.Miasta.FindAsync(id);
            if (miasto != null)
            {
                _context.Miasta.Remove(miasto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MiastoExists(int id)
        {
          return (_context.Miasta?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ASP_NET_INMN3_PA1.1+sp_wszyscy_Z2/Controllers/WitajController.cs
using Microsoft.AspNetCore.Mvc;
using ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Models;

namespace ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Controllers;
public class WitajController : Controller
{
    public IActionResult Index(string? id)
    {
        if(id == null)
            ViewData["Komunikat"] = "nie otrzymałem id w zapytaniu";
        else
            ViewData["Komunikat"] = $"id to {id}";
        return View();
    }
    public IActionResult Witaj(string? imię, int? ilość)
    {
        /*ViewData["Imię"] = imię;
        ViewData["Ilość"] = ilość;
        return View()*/
        //powyższe niewskazane, często wymaga rzutowania

        /*return View(
            (Imię: imię, Ilość: ilość)
            );*/
        //powyższe jest lepsze, o ile w widoku zadeklarujemy model

        return View(
            new WitajViewModel() { Imię = imię, Ilość = ilość }
            );
    }
}

ASP_NET_INMN3_PA1.1+sp_wszyscy_Z2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASP_NET_INMN3_PA1.1+sp_wszyscy_Z2/Views/Miasta/Create.cshtml
@model ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Models.Miasto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Miasto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nazwa" class="control-label"></label>
                <input asp-for="Nazwa" class="form-control" />
                <span asp-validation-for="Nazwa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Populacja" class="control-label"></label>
                <input asp-for="Populacja" class="form-control" />
                <span asp-validation-for="Populacja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP_NET_INMN3_PA1.1+sp_wszyscy_Z2/Views/Miasta/Delete.cshtml
@model ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Models.Miasto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Miasto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazwa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Populacja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Populacja)
        </dd>
    </dl>
    
    <form method="POST">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ASP_NET_INMN3_PA1.1+sp_wszyscy_Z2/Views/Miasta/Details.cshtml
@model ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Models.Miasto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Miasto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazwa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Populacja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Populacja)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ASP_NET_INMN3_PA1.1+sp_wszyscy_Z2/Views/Miasta/Edit.cshtml
@model ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Models.Miasto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Miasto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nazwa" class="control-label"></label>
                <input asp-for="Nazwa" class="form-control" />
                <span asp-validation-for="Nazwa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Populacja" class="control-label"></label>
                <input asp-for="Populacja" class="form-control" />
                <span asp-validation-for="Populacja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP_NET_INMN3_PA1.1+sp_wszyscy_Z2/Views/Miasta/Index.cshtml
@model IEnumerable<ASP_NET_INMN3_PA1_1_sp_wszyscy_Z2.Models.Miasto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form>
    <p>
        <label for="szukanaFraza">Wyszukaj w nazwie: </label>
        <input name="szukanaFraza" value="@ViewData["SzukanaFraza"]"/>
        <input type="submit" value="Szukaj"/>
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nazwa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Populacja)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nazwa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Populacja)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ASP_NET_INMN3_PA1.1+sp_wszyscy_Z2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wzorzec MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP_NET_INMN3_PA1._1_sp_wszyscy_Z2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Wzorzec MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Miasta" asp-action="Index">Miasta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Witaj" asp-action="Index">Test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Witaj" asp-action="Witaj">Powitanie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Wzorzec MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASP_NET_INMN3_PA1.1+sp_wszyscy_Z2/Views/Witaj/Index.cshtml
@{
    ViewData["Title"] = "Test";
}
<p>@ViewData["Komunikat"]</p>

ASP_NET_INMN3_PA1.1+sp_wszyscy_Z2/Views/Witaj/Witaj.cshtml
@*@model (string? Imię, int? Ilość)*@
@model WitajViewModel;
@{
    ViewData["Title"] = "Powitanie";
}

@for(int i = 0; i < Model.Ilość; i++)
{
    <p>Witaj, <strong>@Model.Imię</strong>!</p>
}